spring:
  application:
    name: user-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: user-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:18761/eureka}
    import: 'optional:configserver:'


keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:13300}
  realm: ${REALM:my-realm}
  username: ${KEYCLOAK_USERNAME:admin}
  password: ${KEYCLOAK_PASSWORD:admin}
  client-id: ${KEYCLOAK_CLIENT_ID:loopang-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

topics:
  user:
    updated: ${TOPICS_USER_UPDATED:user-update-topic}