spring:
  application:
    name: user-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:18761/eureka}
    import: 'optional:configserver:'


keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:3300}
  realm: ${REALM:my-realm}
  username: ${KEYCLOAK_USERNAME:admin}                   # 기본 Keycloak 관리자 계정 ID
  password: ${KEYCLOAK_PASSWORD:admin}                   # 기본 Keycloak 관리자 계정 PW
  client-id: ${KEYCLOAK_CLIENT_ID:admin-cli}             # 기본 제공되는 관리용 클라이언트 ID